import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Links from "../components/Links";
import NavBar from "../components/NavBar";
import Section from "../components/Section";
import Service from "../components/Service";
import ServiceCard from "../components/ServiceCard";
import SplitScreens from "../components/SplitScreens";
import styles from "../styles/Home.module.css";

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>ANANAB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar
          children={[
            <Links name="About" dir="about" />,
            <Links name="Contact" dir="contact" />,
          ]}
        />
        <Hero />
        <Section title="Services" description="what we offer" />
        <Service />
        <Section title="About Us" description="Who we are" />
        <SplitScreens
          children={[
            <ServiceCard
              btnName="Talk to us"
              description="Good things happen when people can move, whether across town or toward their dreams. Opportunities appear, open up, become reality. What started as a way to tap a button to get a ride has led to billions of moments of human connection as people around the world go all kinds of places in all kinds of ways with the help of our technology."
            />,
            <img classNameName="w-full md:w-4/5 z-50" src="hero.png" />,
          ]}
        />

        {/* <h1 classNameName={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p classNameName={styles.description}>
          Get started by editing{' '}
          <code classNameName={styles.code}>pages/index.js</code>
        </p>

        <div classNameName={styles.grid}>
          <a href="https://nextjs.org/docs" classNameName={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" classNameName={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            classNameName={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            classNameName={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer classNameName={styles.footer}>
        <a
          href="https://michina.netlify.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span classNameName={styles.logo}>
            <img src="/ananab.svg" width="150" height="40" />
          </span>
        </a>
      </footer>
    </div>
  );
}
